name: Build Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Production Image
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: zavestudios/platform-pipelines/.github/workflows/container-build.yml@c0aa80bb405fa24ede5ebcf1c40b0be90328386c
    with:
      context: .
      dockerfile: production.Dockerfile
      image_name: zavestudios/thehouseguy
      push: false
      platforms: linux/amd64
